### ISSUE TITLE
ENH: Add README.md

### ISSUE THREAD

**Issue by VictorOmondiCDS** [PurityNyakundi/HeartKaggle#1]
Hello @PurityNyakundi , it would be nice if you could add README.md file in this repository for other people to know what this project is about and what you are trying to achieve.

## What is README.md?

Nice **question**, take a look at [this website](https://www.makeareadme.com/) to learn more on README.md

If you have any questions I'm always available to help where applicable.

**Comment by PurityNyakundi** [comment]
I know all about read me . I just don't like putting it

pure

**Comment by VictorOmondiCDS** [comment]
How can we understand and contribute to this🤔
